openapi: 3.0.0
info:
  title: Clean Architecture API
  description: Testes das rotas de Assunto, Disciplina e Conteúdo
  version: 1.0.0

servers:
  - url: http://localhost:3000
    description: Local environment

components:
  schemas:
    Disciplina:
      type: object
      properties:
        nome:
          type: string
      required:
        - nome
    
    Assunto:
      type: object
      properties:
        nome:
          type: string
        disciplinaID:
          type: string
      required:
        - nome
        - disciplinaID
    
    Conteudo:
      type: object
      properties:
        assuntoId:
          type: string
        nivel:
          type: string
          enum: [iniciante, intermediario, avancado]
        formato:
          type: string
          enum: [texto, video, exercicio]
      required:
        - assuntoId
        - nivel
        - formato

paths:
  /disciplinas:
    post:
      summary: Criar Disciplina
      tags:
        - Disciplinas
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Disciplina'
            example:
              nome: "Matemática"
      responses:
        '201':
          description: Disciplina criada com sucesso
    
    get:
      summary: Listar Disciplinas
      tags:
        - Disciplinas
      responses:
        '200':
          description: Lista de disciplinas

  /assuntos:
    post:
      summary: Criar Assunto
      tags:
        - Assuntos
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Assunto'
            example:
              nome: "Equações do 1º Grau"
              disciplinaID: "{disciplina_id}"
      responses:
        '201':
          description: Assunto criado com sucesso
    
    get:
      summary: Listar Assuntos
      tags:
        - Assuntos
      responses:
        '200':
          description: Lista de assuntos

  /conteudos:
    post:
      summary: Solicitar Geração de Conteúdo
      tags:
        - Conteúdos
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Conteudo'
            example:
              assuntoId: "{assunto_id}"
              nivel: "iniciante"
              formato: "texto"
      responses:
        '201':
          description: Requisição de conteúdo criada

  /conteudos/{request_id}:
    get:
      summary: Obter Conteúdo Gerado
      tags:
        - Conteúdos
      parameters:
        - name: request_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Conteúdo gerado

  /conteudos/{request_id}/status:
    get:
      summary: Verificar Status do Conteúdo
      tags:
        - Conteúdos
      parameters:
        - name: request_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Status do conteúdo